### ISSUE TITLE
Users can view posts

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/final-Project#1]
## 📐 Functionality

> ##### Users will be able to see posts that they or others have posted 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/43438792/171292291-406c7210-c7ae-4556-a606-cd699f4d9131.png)
![image](https://user-images.githubusercontent.com/43438792/171295674-54b27015-9af2-419a-83f1-3ae60fff1758.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Initial setup of schema.sql to create all tables
- [ ] Add dummy data to data.sql to test with

### ☁️ Server

- [ ] Create endpoint GET /api/posts to fetch posts from database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component for the main page `ViewMemes`
- [ ] Create a component for the nav bar `Nav`
- [ ] Create a component for the main image `Meme`
- [ ] Create a component for the comment form `CommentForm`

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
