### ISSUE TITLE
User can post images/ videos

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/final-Project#3]
## ⚙️ Feature

User can post images/ videos

## 📐 Functionality

User can upload images or videos to the app for all other user to see in either the main collective page or in their profiles

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/43438792/171298826-3745af87-f514-45fd-b607-0043e6c2b3db.png)
![image](https://user-images.githubusercontent.com/43438792/171298847-7f71f637-e5a8-48dc-bdd7-a81f7037c19e.png)
![image](https://user-images.githubusercontent.com/43438792/171298869-52e9254d-8a8c-468a-9585-77b428c0b86e.png)
![image](https://user-images.githubusercontent.com/43438792/171298905-69bbc66d-8936-4ad2-82b8-ae8d864ee4f0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Create endpoint POST /api/posts to save a user created post to database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to upload images or videos `Upload`
- [ ] Create a component for adding text to an image `EditText`
- [ ] Create a component for editing the filter for an image `EditFilter`
- [ ] Create a component for submitting a new meme `Submit`

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
